### PR TITLE
Solved Back Press Issue, Enhanced UI, Added Loading Dialog when Loading Data, Added Animated Splash Screen.

### PR DESCRIPTION
**Pull request by prasoonsoni**
Solved Back Press Issue for both MainActivity and StartActivity, Enhanced some of the UI Components, solved constraint layout issues, Added some new fonts for good UI, Created customizable alert dialog when weather data is loading and added animations on splash screen.

### CODE REVIEW

**Comment by Jatin887** [comment]
@prasoonsoni back press issue is already solved just remove that and create a new pr

**Comment by prasoonsoni** [comment]
Ok, Sure

**Comment by jazxii** [comment]
Hey @prasoonsoni , also we have people assigned working on Enhanced UI #11 #2 , and Animated Splash screen #29.
So we will only be able to accept a PR of Added Loading Dialog.

**Comment by prasoonsoni** [comment]
So should I do that Added Loading Dialog PR Again?

**Comment by jazxii** [comment]
@prasoonsoni ofc, you can do it.

**Pull request closed without merging**
