### PR TITLE
have added toast for invalid city name inputs.

### PR DESCRIPTION
**Pull request by avikkundu**
Now, if a invalid input is given, a toast will appear.

### CODE REVIEW

**Comment by avikkundu** [comment]
> Now, if a invalid input is given, a toast will appear.

**Review by Ishan-001 — CHANGES_REQUESTED** [review]
You have changed a lot of files. You can only change the files in the 'app' folder.

**Comment by Ishan-001** [comment]
Kindly pull the code before working on the issue again. Good luck!!

**Comment by avikkundu** [comment]
want to work on it

**Comment by avikkundu** [comment]
have progreesed.please assign it to me

**Pull request closed without merging**
