### PR TITLE
MainActivity, gradle: Setup Api Key as a build config field

### PR DESCRIPTION
**Pull request by oddlyspaced**
* Hardcoding the key can lead to privacy issues in an actual production app, and it is a good development process to leave out the keys from the actual source classes itself. Having the key in gradle file as a build config field would ensure easy replacement in future and can be even replaced with a place holder value without any issue

### CODE REVIEW

**Comment by Ishan-001** [comment]
Cool addition @oddlyspaced , but you deleted the 'runConfigurations.xml' file. Kindly restore it.

**Comment by oddlyspaced** [comment]
I'll go ahead and do that.

**Review by Ishan-001 — CHANGES_REQUESTED** [review]
Restore 'runConfigurations.xml'

**Comment by oddlyspaced** [comment]
Edited my commited, and restored the xml file. Should be good to go.

**Pull request closed without merging**
