### PR TITLE
Added an animation effect to SplashActivity

### PR DESCRIPTION
**Pull request by kritika-sharma130**

### CODE REVIEW

**Comment by kritika-sharma130** [comment]
Kindly merge it. It will provide a sense of motivation to me as its my first ever pull request

**Comment by rohanbabbar04** [comment]
The Handler method can be replaced with the new Splash Screen Android 12 update would be better if this is used 
https://developer.android.com/about/versions/12/splash-screen-migration

**Comment by kritika-sharma130** [comment]
> The Handler method can be replaced with the new Splash Screen Android 12 update would be better if this is used https://developer.android.com/about/versions/12/splash-screen-migration

What should i do? Please guide.

**Comment by kritika-sharma130** [comment]
Is there any issue in merging this code?

**Comment by rohanbabbar04** [comment]
Handler method is not the accurate one 
This was introduced to make splash screen deployment easier

**Comment by kritika-sharma130** [comment]
Can you please guide me on how to do this.I am not aware of this if you can
then i will be highly obliged to you.

**Comment by Jatin887** [comment]
@kritika-sharma130 we apperciate your efforts but this issue is already solved you can take another issues .
All the best

**Pull request closed without merging**
